{% set version = "2.0.11" %}
{% set sha256sum = "efe49a349d4a518be6b6c6b255d4a80f740a341544bde1a807707c058b88d0bd" %}

package:
  name: cymem
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cymem/cymem-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - cymem
  commands:
    - python -m pytest --tb=native --pyargs cymem

about:
  home: https://github.com/explosion/cymem
  license: MIT
  license_file: LICENSE
  summary: Manage calls to calloc/free through Cython
  description: |
    cymem provides two small memory-management helpers for Cython. They make it
    easy to tie memory to a Python object’s life-cycle, so that the memory is
    freed when the object is garbage collected.

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - conda-forge/spacy
